---
- name: Ensure bridge-utils are installed
  apt:
    name: bridge-utils
    state: present

- name: Ensure interface configuration is deployed
  template:
    src: '{{ "etc/network/interfaces.d/{{ ifname }}.j2" }}'
    dest: '/etc/network/interfaces.d/{{ ifname }}'
  notify: Restart interface
