---
- name: Confiure DHCP server
  vars:
    pyexp: 'functools.reduce(bool.__or__, [ ("dhcp" in iface) for iface in data ], False)'
    has_dhcp_iface: '{{ interfaces.values() | python(pyexp) }}'
  block:
  - name: Ensure DHCP server is configured
    import_tasks:
      file: dhcp.yml
    tags: dhcp_server
    when: has_dhcp_iface

  - name: Ensure dhcp server is not installed
    apt:
      name: isc-dhcp-server
      state: absent
    tags: dhcp_server
    when: not has_dhcp_iface
