---
- name: Restart virtual interface
  shell: |
    ifdown {{ ifname }} || (ip link set down {{ ifname }} && ip link del {{ ifname }}) || true
    ifup {{ ifname }}

- name: Restart physical interface
  shell: |
    ifdown {{ ifname }} || ip link set down {{ ifname }} || true
    ifup {{ ifname }}
