---
- hosts: pops
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
    mss: 1340
    monitoring_hosts:
      - 90.187.100.197/32
      - 2a02:8106:19:4900::/56
  roles:
    - base
    - bgp
    - { role: bgp_announce, vars: { ipv4: { net: '{{ ipv4_net }}' } } }
    - { role: bgp_announce, vars: { ipv6: { net: '{{ ipv6_net }}' } } }
    - asn_interfaces
    - { role: munin-node, vars: { allow: '{{ monitoring_hosts }}' } }
    - dhcp_server
    - radvd
    - clamp_mss
    - peerings_direct
    - peerings_ibgp

- hosts: vultr
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
  roles:
    - peering_vultr

- hosts: public_dns
  vars:
    any_ipv4: 44.190.22.53
    any_ipv6: 2a06:e881:5608:ffff::53
  roles:
    - { role: unbound, vars: { unbound: { listen_ipv4: '{{ any_ipv4 }}', listen_ipv6: '{{ any_ipv6 }}' } } }
