---
- hosts: pops
  gather_facts: no
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
    mss: 1340
    monitoring_hosts:
      - 90.187.100.197/32
      - 2a02:8106:19:4900::/56
  roles:
    - base
    - bgp
    - { role: bgp_announce, vars: { announce: { ipv4: { net: '{{ ipv4_net }}' } } } }
    - { role: bgp_announce, vars: { announce: { ipv6: { net: '{{ ipv6_net }}' } } } }
    - asn_interfaces
    - bgp_manual
    - { role: munin-node, vars: { allow: '{{ monitoring_hosts }}' } }
    - dhcp_server
    - radvd
    - clamp_mss
    - peerings_direct
    - peerings_ibgp

- hosts: vultr
  gather_facts: no
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
  roles:
    - peering_vultr

- hosts: public_dns
  gather_facts: no
  vars:
    any_ipv4: 44.190.22.53
    any_ipv6: 2a06:e881:5608:ffff::53
  roles:
    - { role: unbound, vars: { unbound: { listen_ipv4: '{{ any_ipv4 }}', listen_ipv6: '{{ any_ipv6 }}' } } }

- hosts: dns
  gather_facts: no
  vars:
    asn: 208340
    all_knowing_dns:
      listen:
        - 44.190.22.52
        - 2a06:e881:5608:ffff::52
    powerdns:
      listen:
        ipv4: 44.190.22.54
        ipv6: 2a06:e881:5608:ffff::54
      domains:
        - domain: as208340.net
          ttl: 3600
          records:
            as208340.net:
              - soa: 'ns1.as208340.net hostmaster.as208340.net 20190926 7200 3600 1209600 3600'
  roles:
    - all_knowing_dns
    - powerdns
