---
- hosts: pops
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
  roles:
    - base
    - bgp
    - { role: bgp_announce, vars: { ipv4: { net: '{{ ipv4_net }}' } } }
    - { role: bgp_announce, vars: { ipv6: { net: '{{ ipv6_net }}' } } }
    - { role: asn_interface }
    - peerings_direct
    - peerings_ibgp
    - role: munin
      vars: 
        allow: [138.201.47.81/32, 2a01:4f8:171:2bec::81/128]
      tags: 'munin'

- hosts: vultr
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
  roles:
    - peering_vultr
