---
- hosts: pops
  gather_facts: no
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
    mss: 1340
    monitoring_hosts:
      - 90.187.100.197/32
      - 2a02:8106:19:4900::/56
    radvd:
      dns_nameservers: 2a06:e881:5608:FFFF::53
      dns_searchlist_domains: as208340.net
  roles:
    - base
    - bgp
    - { role: bgp_announce, vars: { announce: { ipv4: { net: '{{ ipv4_net }}' } } } }
    - { role: bgp_announce, vars: { announce: { ipv6: { net: '{{ ipv6_net }}' } } } }
    - asn_interfaces
    - bgp_manual
    - { role: munin-node, vars: { allow: '{{ monitoring_hosts }}' } }
    - dhcp_server
    - radvd
    - clamp_mss
    - peerings_direct
    - peerings_ibgp

- hosts: vultr
  gather_facts: no
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
  roles:
    - peering_vultr

- hosts: public_dns
  gather_facts: no
  vars:
    any_ipv4: 44.190.22.53
    any_ipv6: 2a06:e881:5608:ffff::53
  roles:
    - { role: unbound, vars: { unbound: { listen_ipv4: '{{ any_ipv4 }}', listen_ipv6: '{{ any_ipv6 }}' } } }

- hosts: dns
  gather_facts: no
  vars:
    asn: 208340
    all_knowing_dns:
      listen:
        - 44.190.22.52
        - 2a06:e881:5608:ffff::52
    powerdns:
      listen:
        ipv4: 44.190.22.54
        ipv6: 2a06:e881:5608:ffff::54
      domains:
        - domain: as208340.net
          ttl: 3600
          records:
            as208340.net:
              - soa: 'ns1.as208340.net as208340.t-sys.eu 2019100100 7200 3600 1209600 3600'
              - ns: ns1.as208340.net
              - ns: ns2.as208340.net
            ns1.as208340.net:
              - a: 44.190.22.54
              - aaaa: 2a06:e881:5608:ffff::54
            ns2.as208340.net:
              - a: 44.190.22.54
              - aaaa: 2a06:e881:5608:ffff::54
            rdns1.as208340.net:
              - a: 44.190.22.52
              - aaaa: 2a06:e881:5608:ffff::52
            rdns2.as208340.net:
              - a: 44.190.22.52
              - aaaa: 2a06:e881:5608:ffff::52
            dns.anycast.as208340.net:
              - a: 44.190.22.54
              - aaaa: 2a06:e881:5608:ffff::54
            resolver.anycast.as208340.net:
              - a: 44.190.22.53
              - aaaa: 2a06:e881:5608:ffff::53
            rdns.anycast.as208340.net:
              - a: 44.190.22.52
              - aaaa: 2a06:e881:5608:ffff::52

        - domain: 8.0.6.5.1.8.8.e.6.0.a.2.ip6.arpa
          ttl: 3600
          records:
            8.0.6.5.1.8.8.e.6.0.a.2.ip6.arpa:
              - soa: 'ns1.as208340.net as208340.t-sys.eu 2019100101 7200 3600 1209600 3600'
              - ns: ns1.as208340.net
              - ns: ns2.as208340.net
            9.2.1.0.8.0.6.5.1.8.8.e.6.0.a.2.ip6.arpa:
              - ns: rdns1.as208340.net
              - ns: rdns2.as208340.net
            4.5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.f.f.f.8.0.6.5.1.8.8.e.6.0.a.2.ip6.arpa:
              - ptr: dns.anycast.as208340.net.
            3.5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.f.f.f.8.0.6.5.1.8.8.e.6.0.a.2.ip6.arpa:
              - ptr: resolver.anycast.as208340.net.
            2.5.0.0.0.0.0.0.0.0.0.0.0.0.0.0.f.f.f.f.8.0.6.5.1.8.8.e.6.0.a.2.ip6.arpa:
              - ptr: rdns.anycast.as208340.net.

  roles:
    - all_knowing_dns
    - powerdns
