---
- hosts: pops
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
  roles:
    - base
    - bgp
    - { role: bgp_announce, vars: { ipv4: { net: '{{ ipv4_net }}' } } }
    - { role: bgp_announce, vars: { ipv6: { net: '{{ ipv6_net }}' } } }
    - { role: asn_interface }

  tasks:
    - name: Establish ibgp peerings
      include_role:
        name: peering_ibgp
      vars:
        peername: '{{ item }}'
        ipv4_primary: '{{ interfaces["as" ~ asn].ipv4 }}'
        ipv6_primary: '{{ interfaces["as" ~ asn].ipv6 }}'
      with_items: '{{ groups["pops"] }}'
      when: item != inventory_hostname
      tags: peering_ibgp
  
- hosts: vultr
  vars:
    asn: 208340
    ipv4_net: 44.190.22.0/24
    ipv6_net: 2a06:e881:5608::/48
  roles:
    - peering_vultr
