---
- hosts: pops
  vars:
    asn: <asn here>
    ipv4_net: <ipv4 net here>
    ipv6_net: <ipv6 net here>
    mss: <TCP mss that can be forwarded>
    monitoring_hosts:
      - <host 1>
      - <host 2>
  roles:
    - base
    - bgp
    - { role: bgp_announce, vars: { announce: { ipv4: { net: '{{ ipv4_net }}' } } } }
    - { role: bgp_announce, vars: { announce: { ipv6: { net: '{{ ipv6_net }}' } } } }
    - { role: asn_interface }
    - { role: munin-node, vars: { allow: '{{ monitoring_hosts }}' } }
    - clamp_mss
    - peerings_direct
    - peerings_ibgp

- hosts: vultr
  vars:
    asn: <asn here>
    ipv4_net: <ipv4 net here>
    ipv6_net: <ipv6 net here>
  roles:
    - peering_vultr

- hosts: dhcp
  vars: 
    dns_nameservers: [2001:4860:4860::8888, 2001:4860:4860::8844]
    dns_searchlist_domain: "<dns searchdomain here>"
  roles:
    - radvd

- hosts: dns
  vars:
    rdns_listen: 
      - <ipv4 net here>
      - <ipv6 net here>
  roles: 
    - all_knowing_dns
