---
- hosts: pops
  vars:
    asn: <asn here>
    ipv4_net: <ipv4 net here>
    ipv6_net: <ipv6 net here>
    monitoring_hosts:
      - <host 1>
      - <host 2>
  roles:
    - base
    - bgp
    - { role: bgp_announce, vars: { ipv4: { net: '{{ ipv4_net }}' } } }
    - { role: bgp_announce, vars: { ipv6: { net: '{{ ipv6_net }}' } } }
    - { role: asn_interface }
    - { role: munin-node, vars: { allow: '{{ monitoring_hosts }}' } }
    - peerings_direct
    - peerings_ibgp

- hosts: vultr
  vars:
    asn: <asn here>
    ipv4_net: <ipv4 net here>
    ipv6_net: <ipv6 net here>
  roles:
    - peering_vultr
