---
- hosts: pops
  vars:
    asn: <asn here>
    ipv4_net: <ipv4 net here>
    ipv6_net: <ipv6 net here>
    mss: <TCP mss that can be forwarded>
    monitoring_hosts:
      - <host 1>
      - <host 2>
  roles:
    - base
    - bgp
    - { role: bgp_announce, vars: { announce: { ipv4: { net: '{{ ipv4_net }}' } } } }
    - { role: bgp_announce, vars: { announce: { ipv6: { net: '{{ ipv6_net }}' } } } }
    - asn_interfaces
    - { role: munin-node, vars: { allow: '{{ monitoring_hosts }}' } }
    - clamp_mss
    - peerings_direct
    - peerings_ibgp

- hosts: vultr
  vars:
    asn: <asn here>
    ipv4_net: <ipv4 net here>
    ipv6_net: <ipv6 net here>
  roles:
    - peering_vultr

- hosts: dhcp
  vars: 
    radvd:
      dns_nameservers: [ <nameserver 1>, <nameserver 2> ] # Optional, either list or sigle entry
      dns_searchlist_domains: [ <dns searchdomain 1>, <dns searchdomain 2> ] # Optional, list of searchdomains, either list or single entry
  roles:
    - radvd

- hosts: dns
  vars:
    all_knowing_dns:
      listen:
        - <ipv4 net here>
        - <ipv6 net here>
      networks: # Optional
        - net:  "<ipv6 network here>"
          hostname: "%DIGITS%.<domain_name>"
          upstream: "<ipv6 address of upstream server>" # Optional
    powerdns:
      listen:
        ipv4: <ipv4 address here> # Optional
        ipv6: <ipv6 address here> # Optional
      domains:
        - domain: <your domain>
          ttl: <default ttl>
          records:
            <name>:
              - <type>: <content> # DNS resource record
              - <type>: { ttl: <ttl>, content: <content> } # DNS resource record with no-default ttl
  roles: 
    - all_knowing_dns
