---
- name: Ensure munin-node is installed
  apt:
    name: munin-node
    state: present

- name: Ensure libnet-cidr-perl is installed
  apt:
    name: libnet-cidr-perl
    state: present

- name: Ensure libcommon-sense-perl is installed
  apt:
    name: libcommon-sense-perl
    state: present

- name: Configure munin-node
  template:
    src: etc/munin/munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    mode: 0700
  notify: Restart munin-node

- name: Ensure /usr/local/share/munin/plugins exists
  file:
    path: /usr/local/share/munin/plugins
    state: directory

- name: Ensure munin-node bird plugin is set up
  import_tasks:
    file: bird.yml

- name: Ensure munin-node unbound plugin is set up
  import_tasks:
    file: unbound.yml

- name: Ensure munin-node service is enabled and started
  service:
    name: munin-node
    enabled: yes
    state: started
