---
- name: Ensure IPv6 BGP connections from vultr are allowed
  template:
    src:  etc/iptables.d/500-allow-BGP6-vultr.conf.j2
    dest: /etc/iptables.d/500-allow-BGP6-vultr.conf
  notify: Restart iptables daemon

- name: Ensure IPv6 vultr peering is set up
  template:
    src: etc/bird/peers/vultr-v6.conf.j2
    dest: /etc/bird/peers/vultr-v6.conf
    mode: 0600
    owner: bird
  notify: Reload bird config
