---
- name: Restart virtual interface {{ restart.ifname }}
  shell: |
    ifdown --force {{ restart.ifname }} || (ip link set down {{ restart.ifname }} && ip link del {{ restart.ifname }}) || true
    ifup {{ restart.ifname }}
  when: restart.virtual | default(False)

- name: Restart physical interface {{ restart.ifname }}
  shell: |
    ifdown --force {{ restart.ifname }} || ip link set down {{ restart.ifname }} || true
    ifup {{ restart.ifname }}
  when: not (restart.virtual | default(False))

