\---
- name: Ensure IPv6 BGP connections from {{ peername }} are allowed
  template:
    src:  '{{ "etc/iptables.d/500-allow-BGP6-peering-{{ peername }}.conf.j2" }}'
    dest: '/etc/iptables.d/500-allow-BGP6-peering-{{ peername }}.conf'
    mode: 0644
  notify: Restart iptables daemon

- name: Ensure IPv6 peering with {{ peername }} is set up
  template:
    src: '{{ "etc/bird/bird6/peers/direct-{{ peername }}.conf.j2" }}'
    dest: /etc/bird/bird6/peers/direct-{{ peername }}.conf
    mode: 0600
    owner: bird
  notify: Reload bird6 config
  tags: peerings_direct
