---
- name: Ensure IPv4 BGP connections from {{ peername }} are allowed
  template:
    src:  '{{ "etc/iptables.d/500-allow-BGP4-peering-{{ peername }}.conf.j2" }}'
    dest: '/etc/iptables.d/500-allow-BGP4-peering-{{ peername }}.conf'
    mode: 0644
  notify: Restart iptables daemon

- name: Ensure IPv4 peering with {{ peername }} is set up
  template:
    src: '{{ "etc/bird/peers/direct-{{ peername }}-v4.conf.j2" }}'
    dest: /etc/bird/peers/direct-{{ peername }}-v4.conf
    mode: 0600
    owner: bird
  notify: Reload bird config
  tags: peerings_direct
