---
- name: Ensure peering firewall is set up
  import_role:
    name: peering
  tags: peerings_direct, peering_direct4, peering_direct6  

- name: Ensure IPv4 ingress from {{ peername }} is forwarded through as set table
  template:
    src: '{{ "etc/routing-rules.d/upstream_transitive-{{ peername }}.conf.j2" }}'
    dest: /etc/routing-rules.d/upstream_transitive-{{ peername }}.conf
  notify: Restart routing rule daemon
  when: peering.type is defined and peering.type == "upstream_transitive"

- name: Ensure IPv4 direct peering with {{ peername }} is set up
  import_tasks:
    file: direct4.yml
  when: peering.peer.ipv4 is defined
  tags: peerings_direct, peering_direct4

- name: Ensure IPv6 direct peering with {{ peername }} is set up
  import_tasks:
    file: direct6.yml
  when: peering.peer.ipv6 is defined
  tags: peerings_direct, peering_direct6
