---
- name: Ensure interface {{ interface.name }} is configured
  vars:
    ifname: '{{ interface.name }}'
  template:
    src:  '{{ "etc/network/interfaces.d/{{ ifname }}.j2" }}'
    dest: '/etc/network/interfaces.d/{{ ifname }}'
  register: ensure_interface
  tags: interface

- name: Restart {{ interface.name }}
  vars:
    ifname: '{{ interface.name }}'
    virtual: '{{ interface.virtual | default(False) }}'
  import_role:
    name: restart_interface
  when: ensure_interface.changed
  tags: interface
