---
- name: Ensure interface {{ ifname }} is configured
  template:
    src:  '{{ "etc/network/interfaces.d/{{ ifname }}.j2" }}'
    dest: '/etc/network/interfaces.d/{{ ifname }}'
  tags: interface
  notify: Restart physical interface

- name: Force execution of handlers
  meta: flush_handlers
  tags: interface
