---
- name: Ensure interface {{ interface.name }} is configured
  vars:
    ifname: '{{ interface.name }}'
  template:
    src:  '{{ "etc/network/interfaces.d/{{ ifname }}.j2" }}'
    dest: '/etc/network/interfaces.d/{{ ifname }}'
  notify: '{{ "Restart virtual interface" if interface.virtual is defined and interface.virtual else "Restart physical interface" }}'
  tags: interface

- name: Force execution of handlers
  meta: flush_handlers
  tags: interface
