---
- name: Ensure IPv6 announcement config is preset
  template:
    src: '{{ "etc/bird/conf.d/100-announce-{{ net_sanitized }}-v6.conf.j2" }}'
    dest: '/etc/bird/conf.d/100-announce-{{ net_sanitized }}-v6.conf'
    mode: 0644
  vars:
    net_sanitized: '{{ announce.ipv6.net | regex_replace("/", "_") }}'
  notify: Reload bird config
