---
- name: Announce an IPv4 network
  import_tasks:
    file: announce4.yml
  when: announce.ipv4 is defined
  tags: bgp_announce, bgp_announce4

- name: Announce an IPv6 network
  import_tasks:
    file: announce6.yml
  when: announce.ipv6 is defined
  tags: bgp_announce, bgp_announce6
