#!/usr/bin/env bash

set -e -o pipefail

RULE_DIR='/etc/routing-rules.d'

warn() {
  ( 1>&2 echo $@ )
}

if [ -d "$RULE_DIR" ]; then
  warn Rule directory "\"$RULE_DIR\"" does not exist
  exit 1
fi

base64 --decode <<'EOF' | ip -4 rule restore
hmlwcTQAAAAgAAIAdMl6XSEGAAACAAAA/wAAAQAAAAAIAA8A/wAAAAgADgD/////BQAVAAIAAAA8
AAAAIAACAHTJel0hBgAAAgAAAP4AAAEAAAAACAAPAP4AAAAIAA4A/////wUAFQACAAAACAAGAP5/
AAA8AAAAIAACAHTJel0hBgAAAgAAAP0AAAEAAAAACAAPAP0AAAAIAA4A/////wUAFQACAAAACAAG
AP9/AAA=
EOF

base64 --decode <<'EOF' | ip -6 rule restore
hmlwcTQAAAAgAAIACsp6XSoGAAAKAAAA/wAAAQAAAAAIAA8A/wAAAAgADgD/////BQAVAAIAAAA8
AAAAIAACAArKel0qBgAACgAAAP4AAAEAAAAACAAPAP4AAAAIAA4A/////wUAFQACAAAACAAGAP5/
AAA=
EOF

for file in "$RULE_DIR"/*.conf; do
  echo Running rules file "\"$file\""
  if ! "$file"; then
    warn Execution of rules from "\"$file\"" failed
  fi
done
