---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  listen: Restart bird-exporter daemon

- name: Restart bird-exporter daemon
  service:
    name: bird-exporter
    state: restarted

- name: Restart iptables daemon
  service:
    name: iptablesd
    state: restarted
