---
- name: Ensure radvd is installed
  vars:
    pyexp: 'functools.reduce(bool.__or__, [ (iface["radvd"] if "radvd" in iface else False) for iface in data ], False)'
    has_radvd_iface: '{{ interfaces.values() | python(pyexp) }}'
  import_tasks:
    file: radvd.yml
  tags: radvd
