---
- name: Ensure radvd is installed
  vars:
    has_radvd: '{% for iface in (interfaces.values() | debug()) if (iface.radvd | default(False)) %}"True"{% endfor %}'
  import_tasks:
    file: radvd.yml
  tags: radvd
  when: (has_radvd | length) > 0
