---
- name: Ensure radvd is installed
  apt:
    name: radvd
    state: present
  when: has_radvd_iface

- name: Ensure radvd is configured
  template:
    src: etc/radvd.conf.j2
    dest: /etc/radvd.conf
    mode: 0644
  notify: Restart radvd
  when: has_radvd_iface

# Handle service
- name: Ensure radvd service is enabled and started
  service:
    name: radvd
    enabled: yes
    state: started
  when: has_radvd_iface

- name: Ensure radvd service is disabled and stopped
  service:
    name: radvd
    enabled: no
    state: stopped
  when: not has_radvd_iface
