---
- name: Ensure static protocol (IPv6) is deployed
  vars:
    ifname: '{{ item.key }}'
    ipv6_addresses: '{{ item.value.ipv6 if item.value.ipv6 | is_list else [ item.value.ipv6 ] }}'
  template:
    src:  '{{ "etc/bird/conf.d/100-announce-{{ ifname }}-v6.conf.j2" }}'
    dest: '/etc/bird/conf.d/100-announce-{{ ifname }}-v6.conf'
    mode: 0644
  notify: Reload bird config
  loop: '{{ interfaces | dict2items }}'
  when: item.value.announce is defined and item.value.announce
