---
# Install BGP firewall filter
- name: Ensure IPv4 BGP firwall filter is deployed
  copy:
    src: etc/iptables.d/900-block-BGP4.conf
    dest: /etc/iptables.d/900-block-BGP4.conf
  notify: Restart iptables daemon

- name: Ensure IPv6 BGP firwall filter is deployed
  copy:
    src: etc/iptables.d/900-block-BGP6.conf
    dest: /etc/iptables.d/900-block-BGP6.conf
  notify: Restart iptables daemon

# Build directory structure
- name: Ensure bird dir exists
  file:
    path: /etc/bird/
    state: directory

- name: Ensure bird define dir exists
  file:
    path: /etc/bird/defines
    state: directory

- name: Ensure bird config dir exists
  file:
    path: /etc/bird/conf.d
    state: directory

- name: Ensure bird filter dir exists
  file:
    path: /etc/bird/filters
    state: directory

- name: Ensure bird peer dir exists
  file:
    path: /etc/bird/peers
    state: directory

- name: Ensure bird local defines are present
  template:
    src: etc/bird/defines/010-local.conf.j2
    dest: /etc/bird/defines/010-local.conf
    mode: 0644
  notify: Reload bird config

# Handle service
- name: Ensure bird service is enabled and started
  service:
    name: bird
    enabled: yes
    state: started
