---

- name: Ensure 32bit/i386 architecture is enabled
  lineinfile: dest=/var/lib/dpkg/arch line="i386" create=yes
  register: add_i386
  when: bgp.i386_bird | default(False)
  tags: bgp, bird

- name: Ensure bird (32bit/i386) is installed
  apt:
    name: bird2:i386
    state: present
    update_cache: "{{add_i386.changed}}"
  when: bgp.i386_bird | default(False)
  tags: bgp, bird

- name: Ensure bird (native) is installed
  apt:
    name: bird2
    state: present
  when: not (bgp.i386_bird | default(False))
  tags: bgp, bird

- name: Ensure bird config directory exists
  file:
    path: /etc/bird/
    state: directory
  tags: bgp, bird

- name: Ensure bird configs are installed
  copy:
    src: etc/bird/
    dest: /etc/bird
    mode: 0644
  notify:
    - Reload bird config
  tags: bgp, bird

- name: Ensure bird protcols directory exists
  file:
    path: /etc/bird/protocols
    state: directory
  tags: bgp, bird

- name: Ensure bird templates are installed
  template:
    src: etc/bird/protocols/020-templates.conf.j2
    dest: /etc/bird/protocols/020-templates.conf
    mode: 0644
  notify:
    - Reload bird config
  tags: bgp, bird

- name: Configure bird
  import_tasks:
    file: bird.yml
  tags: bgp, bird
