---

- name: Ensure 32bit/i386 architecture is enabled
  lineinfile: dest=/var/lib/dpkg/arch line="i386" create=yes
  register: add_i386
  when: bgp.i386_bird | default(False)
  tags: bgp, bird,  bird4, bird6

- name: Ensure bird (32bit/i386) is installed
  apt:
    name: bird:i386
    state: present
    update_cache: "{{add_i386.changed}}"
  when: bgp.i386_bird | default(False)
  tags: bgp, bird,  bird4, bird6

- name: Ensure bird (native) is installed
  apt:
    name: bird
    state: present
  when: not (bgp.i386_bird | default(False))
  tags: bgp, bird,  bird4, bird6

- name: Ensure common config directory exists
  file:
    path: /etc/bird/common
    state: directory
  tags: bgp, bird, bird4, bird6

- name: Ensure common configs are installed
  copy:
    src: etc/bird/common
    dest: /etc/bird
    mode: 0644
  notify:
    - Reload bird config
    - Reload bird6 config
  tags: bgp, bird, bird4, bird6

- name: Ensure common protcols directory exists
  file:
    path: /etc/bird/common/protocols
    state: directory
  tags: bgp, bird, bird4, bird6

- name: Ensure common templates are installed
  template:
    src: etc/bird/common/protocols/020-templates.conf.j2
    dest: /etc/bird/common/protocols/020-templates.conf
    mode: 0644
  notify:
    - Reload bird config
    - Reload bird6 config
  tags: bgp, bird, bird4, bird6

- name: Configure bird (IPv4)
  import_tasks:
    file: bird.yml
  tags: bgp, bird, bird4

- name: Configure bird6 (IPv6)
  import_tasks:
    file: bird6.yml
  tags: bgp, bird, bird6
