---
- name: Ensure bird is installed
  apt:
    name: bird
    state: present
  tags: bgp, bird

- name: Configure bird (IPv4)
  import_tasks:
    file: bird.yml
  tags: bgp, bird, bird4

- name: Configure bird6 (IPv6)
  import_tasks:
    file: bird6.yml
  tags: bgp, bird, bird6
