---
- name: Setup interface
  vars:
    ifname: '{{ item.key }}'
    iface: '{{ item.value }}'
  include_tasks:
    file: interface-{{ item.value.type }}.yml
  with_items: '{{ interfaces | dict2items }}'
  when: item.value.managed is defined and item.value.managed
