---
- name: Set up physical interface {{ ifname }}
  vars:
    interface:
      name: '{{ ifname }}'
      ipv4: '{{ iface.ipv4 if iface.ipv4 is defined else [] }}'
      ipv6: '{{ iface.ipv6 if iface.ipv6 is defined else [] }}'
  import_role:
    name: interface
  tags: base, interfaces
