---
- name: Setup interfaces
  vars:
    ifname: '{{ item.key }}'
    # Workaround for undefined magic and host variables in certain loop environments
    iface: '{{ item.value | interface_mtu_fixup(ifname, ansible_loop.allitems | items2dict) }}'
  include_tasks:
    file: interface.yml
  loop: '{{ interfaces | dict2items }}'
  loop_control:
    extended: yes
  when: item.value.managed is defined and item.value.managed
