---
- name: Install aptitude
  apt:
    name: aptitude
    state: present
  tags: base

- name: Enable unattended upgrades
  import_tasks:
    file: unattended_upgrades.yml
  tags: base, unattended_upgrades

- name: Set sysctl settings
  import_tasks:
    file: sysctl.yml
  tags: base, sysctl

- name: Setup routing
  import_tasks:
    file: routing.yml
  tags: base, routing

- name: Setup interfaces
  import_tasks:
    file: interfaces.yml
  tags: base, interfaces
