#!/usr/bin/env bash

set -e -o pipefail

RULE_DIR='/etc/iptables.d'

IPTABLES="$(command -v iptables)"
IP6TABLES="$(command -v ip6tables)"

if ! "$IPTABLES" -V &> /dev/null; then
	IPTABLES="$(command -v iptables-legacy)"
fi

if ! "$IP6TABLES" -V &> /dev/null; then
	IP6TABLES="$(command -v ip6tables-legacy)"
fi

warn() {
  ( 1>&2 echo $@ )
}

ip4tables() {
  "$IPTABLES" "$@"
}

ip6tables() {
  "$IP6TABLES" "$@"
}

ip46tables() {
  ip4tables "$@"
  ip6tables "$@"
}

if ! [ -d "$RULE_DIR" ]; then
  warn Rule directory "\"$RULE_DIR\"" does not exist
  exit 1
fi

ip4tables -t raw --flush || true
ip4tables -t filter --flush || true
ip4tables -t nat --flush || true
ip4tables -t mangle --flush || true
ip4tables -t security --flush || true

ip6tables -t raw --flush || true
ip6tables -t filter --flush || true
ip6tables -t nat --flush || true
ip6tables -t mangle --flush || true
ip6tables -t security --flush || true

for file in "$RULE_DIR"/*.conf; do
  if ! [ -f "$file" ]; then
    break
  fi
  echo Running rules file "\"$file\""
  if ! (. "$file"); then
    warn Execution of rules from "\"$file\"" failed
  fi
done
