#!/usr/bin/env bash

set -e -o pipefail

RULE_DIR='/etc/iptables.d'

IPTABLES="$(command -v iptables)"
IP6TABLES="$(command -v ip6tables)"

warn() {
  ( 1>&2 echo $@ )
}

ip4tables() {
  "$IPTABLES" "$@"
}

ip6tables() {
  "$IP6TABLES" "$@"
}

ip46tables() {
  ip4tables "$@"
  ip6tables "$@"
}

if ! [ -d "$RULE_DIR" ]; then
  warn Rule directory "\"$RULE_DIR\"" does not exist
  exit 1
fi

iptables -t raw --flush
iptables -t filter --flush
iptables -t nat --flush
iptables -t mangle --flush
iptables -t security --flush

ip6tables -t raw --flush
ip6tables -t filter --flush
ip6tables -t nat --flush
ip6tables -t mangle --flush
ip6tables -t security --flush

for file in "$RULE_DIR"/*.conf; do
  echo Running rules file "\"$file\""
  if ! (. "$file"); then
    warn Execution of rules from "\"$file\"" failed
  fi
done
